// Shared data for streams, roles, and mock projects

export const STREAMS = [
  {
    id: 'film-video',
    name: 'Film & Video',
    icon: '🎬',
    color: 'from-red-500 to-orange-500',
    roles: ['Director', 'Writer', 'Actor', 'Cinematographer', 'Editor', 'VFX Artist', 'Sound Designer', 'Producer'],
  },
  {
    id: 'music',
    name: 'Music',
    icon: '🎵',
    color: 'from-purple-500 to-blue-500',
    roles: ['Musician', 'Producer', 'Vocalist', 'DJ', 'Sound Engineer', 'Lyricist', 'Session Player'],
  },
  {
    id: 'fashion-modelling',
    name: 'Fashion & Modelling',
    icon: '👗',
    color: 'from-pink-500 to-rose-500',
    roles: ['Model', 'Photographer', 'Stylist', 'Makeup Artist', 'Fashion Designer', 'Retoucher'],
  },
  {
    id: 'influencer-content',
    name: 'Influencer & Content',
    icon: '📱',
    color: 'from-cyan-500 to-blue-500',
    roles: ['Content Creator', 'Videographer', 'Editor', 'Social Media Manager', 'Graphic Designer', 'Copywriter'],
  },
  {
    id: 'performing-arts',
    name: 'Performing Arts',
    icon: '🎭',
    color: 'from-amber-500 to-yellow-500',
    roles: ['Theatre Actor', 'Dancer', 'Choreographer', 'Comedian', 'Spoken Word Artist', 'Voice Actor'],
  },
  {
    id: 'visual-arts',
    name: 'Visual Arts',
    icon: '🎨',
    color: 'from-emerald-500 to-teal-500',
    roles: ['Illustrator', 'Animator', '3D Artist', 'Muralist', 'Graphic Designer', 'Art Director'],
  },
  {
    id: 'events-live',
    name: 'Events & Live',
    icon: '🎤',
    color: 'from-violet-500 to-purple-500',
    roles: ['Event Planner', 'DJ', 'Live Performer', 'Host/MC', 'Venue Owner'],
  },
  {
    id: 'brands-businesses',
    name: 'Brands & Businesses',
    icon: '💼',
    color: 'from-slate-400 to-zinc-500',
    roles: ['Marketing Manager', 'Brand Owner', 'Agency', 'Startup Founder'],
  },
] as const;

export type StreamId = typeof STREAMS[number]['id'];

export const MOCK_PROJECTS = [
  {
    id: '1',
    title: 'The Last Bookstore',
    stream: 'Film & Video',
    streamIcon: '🎬',
    genre: 'Drama',
    location: 'London, UK',
    timeline: '4 weeks',
    description: 'In a world where all books are digital, an elderly woman runs the last physical bookstore. A young programmer discovers it and learns what we lose when everything becomes virtual.',
    brief: `## The Last Bookstore\n\nA poignant 8-minute drama exploring the tension between digital progress and human connection.\n\n### Logline\nWhen a tech-obsessed programmer stumbles into the last physical bookstore in London, she discovers that some things can't be digitized — including the lonely woman who runs it.\n\n### Synopsis\nSet in near-future London where physical books have been outlawed as wasteful, MARGARET (72) secretly operates the last bookstore from a hidden basement. When PRIYA (28), a burned-out AI developer, accidentally discovers the shop, she's drawn into Margaret's world of paper, ink, and human stories. As authorities close in, Priya must choose between her comfortable digital life and preserving something irreplaceable.\n\n### Visual Style\nWarm, amber-toned interiors contrasting with cold, blue-lit cityscapes. Handheld intimacy in the bookstore, clinical steadicam in the outside world. References: Her (2013), The Reader (2008).`,
    roles: [
      { role: 'Director', filled: true, member: { name: 'Alex Chen', avatar: '👨‍🎬' } },
      { role: 'Lead Actor (Margaret)', filled: false },
      { role: 'Lead Actor (Priya)', filled: true, member: { name: 'Sana Mirza', avatar: '👩' } },
      { role: 'Cinematographer', filled: false },
      { role: 'Sound Designer', filled: false },
      { role: 'Editor', filled: true, member: { name: 'Jamie Park', avatar: '🧑‍💻' } },
    ],
    teamSize: 6,
    filledRoles: 3,
    status: 'recruiting',
    milestones: [
      { name: 'Pre-production', status: 'active', date: 'Mar 20 – Apr 3' },
      { name: 'Production', status: 'upcoming', date: 'Apr 7 – Apr 12' },
      { name: 'Post-production', status: 'upcoming', date: 'Apr 14 – Apr 28' },
      { name: 'Published', status: 'upcoming', date: 'May 2' },
    ],
    createdAt: '2026-03-15',
  },
  {
    id: '2',
    title: 'Neon Dreams',
    stream: 'Music',
    streamIcon: '🎵',
    genre: 'Electronic / Visual',
    location: 'Manchester, UK',
    timeline: '3 weeks',
    description: 'A surreal music video journey through a cyberpunk city. A dancer moves through neon-lit streets, projections, and mirrors. Heavy post-production VFX.',
    brief: `## Neon Dreams\n\nAn ambitious 3-minute electronic music video blending dance, projection mapping, and VFX.\n\n### Concept\nA dancer awakens in a dark, rain-soaked alley. As the beat drops, the city transforms — walls become screens, puddles become portals, and gravity becomes optional. The dancer's movements control the environment, building to a climactic explosion of light.\n\n### Visual Style\nCyberpunk meets contemporary dance. Neon pinks, electric blues, deep blacks. References: Blade Runner 2049, FKA twigs "Cellophane".`,
    roles: [
      { role: 'Director', filled: false },
      { role: 'Dancer/Performer', filled: true, member: { name: 'Kai Rivera', avatar: '💃' } },
      { role: 'Cinematographer', filled: false },
      { role: 'VFX Artist', filled: false },
      { role: 'Editor', filled: false },
    ],
    teamSize: 5,
    filledRoles: 1,
    status: 'recruiting',
    milestones: [
      { name: 'Pre-production', status: 'active', date: 'Mar 22 – Mar 28' },
      { name: 'Production', status: 'upcoming', date: 'Apr 1 – Apr 3' },
      { name: 'Post-production', status: 'upcoming', date: 'Apr 5 – Apr 15' },
      { name: 'Published', status: 'upcoming', date: 'Apr 18' },
    ],
    createdAt: '2026-03-14',
  },
  {
    id: '3',
    title: 'Blue Hour Workers',
    stream: 'Fashion & Modelling',
    streamIcon: '👗',
    genre: 'Documentary Photography',
    location: 'London, UK',
    timeline: '2 weeks',
    description: 'Portraits of night shift workers during the "blue hour" — that magical time between night and dawn. Capturing quiet dignity of unseen labor.',
    brief: `## Blue Hour Workers\n\nA 20-image documentary photo series capturing London's invisible workforce at dawn.\n\n### Concept\nBetween 4:30-5:30 AM, when the sky turns that impossible shade of blue, London's night workers are finishing their shifts. This series captures bakers, cleaners, nurses, and security guards in that liminal light — tired but resilient, invisible but essential.`,
    roles: [
      { role: 'Photographer', filled: true, member: { name: 'Yuki Tanaka', avatar: '📸' } },
      { role: 'Stylist', filled: false },
      { role: 'Retoucher', filled: false },
    ],
    teamSize: 3,
    filledRoles: 1,
    status: 'recruiting',
    milestones: [
      { name: 'Pre-production', status: 'completed', date: 'Mar 10 – Mar 14' },
      { name: 'Production', status: 'active', date: 'Mar 16 – Mar 23' },
      { name: 'Post-production', status: 'upcoming', date: 'Mar 25 – Mar 30' },
      { name: 'Published', status: 'upcoming', date: 'Apr 2' },
    ],
    createdAt: '2026-03-13',
  },
  {
    id: '4',
    title: 'Street Couture',
    stream: 'Fashion & Modelling',
    streamIcon: '👗',
    genre: 'Editorial Fashion',
    location: 'London, UK',
    timeline: '2 weeks',
    description: 'High fashion meets gritty urban landscapes. A 12-look editorial shoot transforming mundane London locations into runway backdrops.',
    brief: `## Street Couture\n\nA bold editorial series juxtaposing haute couture with raw urban textures.\n\n### Concept\nWhat happens when you put a Valentino gown in a Peckham car park? This series deliberately clashes high fashion with overlooked London spaces — council estates, industrial yards, bus shelters — creating striking visual tension.`,
    roles: [
      { role: 'Photographer', filled: false },
      { role: 'Model', filled: true, member: { name: 'Amara Obi', avatar: '💅' } },
      { role: 'Model', filled: false },
      { role: 'Stylist', filled: true, member: { name: 'Leo Marchetti', avatar: '👔' } },
      { role: 'Makeup Artist', filled: false },
      { role: 'Retoucher', filled: false },
    ],
    teamSize: 6,
    filledRoles: 2,
    status: 'recruiting',
    milestones: [
      { name: 'Pre-production', status: 'active', date: 'Mar 18 – Mar 24' },
      { name: 'Production', status: 'upcoming', date: 'Mar 26 – Mar 28' },
      { name: 'Post-production', status: 'upcoming', date: 'Mar 30 – Apr 5' },
      { name: 'Published', status: 'upcoming', date: 'Apr 8' },
    ],
    createdAt: '2026-03-16',
  },
  {
    id: '5',
    title: 'Unboxed: 60 Seconds',
    stream: 'Influencer & Content',
    streamIcon: '📱',
    genre: 'Social Content Series',
    location: 'Birmingham, UK',
    timeline: '1 week',
    description: 'A series of 10 viral-format product unboxing videos with cinematic production quality. Elevating the unboxing genre into art.',
    brief: `## Unboxed: 60 Seconds\n\nCinematic micro-content that makes product reveals feel like movie trailers.\n\n### Concept\nEach 60-second video transforms a mundane unboxing into a dramatic narrative — suspenseful lighting, ASMR sound design, reveal shots borrowed from thriller cinematography.`,
    roles: [
      { role: 'Content Creator', filled: true, member: { name: 'Zara Ahmed', avatar: '🎥' } },
      { role: 'Videographer', filled: false },
      { role: 'Editor', filled: false },
      { role: 'Sound Engineer', filled: false },
    ],
    teamSize: 4,
    filledRoles: 1,
    status: 'recruiting',
    milestones: [
      { name: 'Pre-production', status: 'completed', date: 'Mar 12 – Mar 14' },
      { name: 'Production', status: 'active', date: 'Mar 16 – Mar 19' },
      { name: 'Post-production', status: 'upcoming', date: 'Mar 20 – Mar 22' },
      { name: 'Published', status: 'upcoming', date: 'Mar 24' },
    ],
    createdAt: '2026-03-11',
  },
  {
    id: '6',
    title: 'Concrete Canvas',
    stream: 'Visual Arts',
    streamIcon: '🎨',
    genre: 'Public Art / Mural',
    location: 'Bristol, UK',
    timeline: '3 weeks',
    description: 'A collaborative mural project transforming a derelict building facade into an interactive AR-enhanced artwork celebrating Bristol\'s music heritage.',
    brief: `## Concrete Canvas\n\nA mural that comes alive through augmented reality, celebrating Bristol's legendary music scene.\n\n### Concept\nA 40ft mural on a derelict warehouse wall in St Pauls, depicting iconic moments from Bristol's music history — from trip-hop to drum & bass. When viewed through a phone camera, the mural animates with sound and motion.`,
    roles: [
      { role: 'Muralist', filled: true, member: { name: 'Banksy Jr', avatar: '🎨' } },
      { role: 'Illustrator', filled: false },
      { role: '3D Artist', filled: false },
      { role: 'Animator', filled: false },
      { role: 'Art Director', filled: false },
    ],
    teamSize: 5,
    filledRoles: 1,
    status: 'recruiting',
    milestones: [
      { name: 'Pre-production', status: 'active', date: 'Mar 20 – Mar 28' },
      { name: 'Production', status: 'upcoming', date: 'Apr 1 – Apr 10' },
      { name: 'Post-production', status: 'upcoming', date: 'Apr 12 – Apr 16' },
      { name: 'Published', status: 'upcoming', date: 'Apr 18' },
    ],
    createdAt: '2026-03-17',
  },
  {
    id: '7',
    title: 'Laugh Track Live',
    stream: 'Performing Arts',
    streamIcon: '🎭',
    genre: 'Comedy / Live Recording',
    location: 'London, UK',
    timeline: '2 weeks',
    description: 'A professionally filmed live comedy showcase featuring 5 emerging comedians. Netflix special quality on an indie budget.',
    brief: `## Laugh Track Live\n\nA slick multi-camera comedy special showcasing London's hottest new stand-up talent.\n\n### Concept\nFive comedians, one intimate venue, three cameras, and world-class sound. Each comedian gets a tight 10-minute set, bookended by cinematic interstitials of them preparing backstage.`,
    roles: [
      { role: 'Comedian', filled: true, member: { name: 'Dev Patel', avatar: '😂' } },
      { role: 'Comedian', filled: false },
      { role: 'Director', filled: false },
      { role: 'Cinematographer', filled: false },
      { role: 'Sound Engineer', filled: false },
      { role: 'Host/MC', filled: false },
    ],
    teamSize: 6,
    filledRoles: 1,
    status: 'recruiting',
    milestones: [
      { name: 'Pre-production', status: 'active', date: 'Mar 19 – Mar 26' },
      { name: 'Production', status: 'upcoming', date: 'Mar 28' },
      { name: 'Post-production', status: 'upcoming', date: 'Mar 30 – Apr 5' },
      { name: 'Published', status: 'upcoming', date: 'Apr 8' },
    ],
    createdAt: '2026-03-18',
  },
  {
    id: '8',
    title: 'The Pop-Up Experience',
    stream: 'Events & Live',
    streamIcon: '🎤',
    genre: 'Immersive Event',
    location: 'London, UK',
    timeline: '4 weeks',
    description: 'A one-night immersive art and music experience in an abandoned warehouse. Think Punchdrunk meets Boiler Room.',
    brief: `## The Pop-Up Experience\n\nAn immersive one-night event fusing live music, interactive art installations, and theatrical performance in an East London warehouse.\n\n### Concept\nGuests enter through a hidden door and navigate through themed rooms — each featuring a different artist, musician, or performer. No phones allowed. What happens inside stays inside.`,
    roles: [
      { role: 'Event Planner', filled: true, member: { name: 'Nina Torres', avatar: '🎪' } },
      { role: 'DJ', filled: false },
      { role: 'Live Performer', filled: false },
      { role: 'Host/MC', filled: false },
      { role: 'Venue Owner', filled: false },
    ],
    teamSize: 5,
    filledRoles: 1,
    status: 'recruiting',
    milestones: [
      { name: 'Pre-production', status: 'active', date: 'Mar 18 – Apr 1' },
      { name: 'Production', status: 'upcoming', date: 'Apr 5' },
      { name: 'Post-production', status: 'upcoming', date: 'Apr 7 – Apr 10' },
      { name: 'Published', status: 'upcoming', date: 'Apr 12' },
    ],
    createdAt: '2026-03-15',
  },
  {
    id: '9',
    title: 'Brand Genesis',
    stream: 'Brands & Businesses',
    streamIcon: '💼',
    genre: 'Brand Campaign',
    location: 'London, UK',
    timeline: '3 weeks',
    description: 'Complete brand launch campaign for an AI-matched startup — from identity design to launch video to social content package.',
    brief: `## Brand Genesis\n\nA full-stack brand launch: visual identity, hero video, and social content suite for a fintech startup.\n\n### Concept\nAI has identified a gap: a new fintech brand needs a complete launch package. This project brings together designers, filmmakers, and content creators to deliver a cohesive brand identity and launch campaign.`,
    roles: [
      { role: 'Marketing Manager', filled: true, member: { name: 'Olivia Hart', avatar: '📊' } },
      { role: 'Graphic Designer', filled: false },
      { role: 'Videographer', filled: false },
      { role: 'Copywriter', filled: false },
      { role: 'Social Media Manager', filled: false },
    ],
    teamSize: 5,
    filledRoles: 1,
    status: 'recruiting',
    milestones: [
      { name: 'Pre-production', status: 'active', date: 'Mar 20 – Mar 28' },
      { name: 'Production', status: 'upcoming', date: 'Apr 1 – Apr 8' },
      { name: 'Post-production', status: 'upcoming', date: 'Apr 10 – Apr 14' },
      { name: 'Published', status: 'upcoming', date: 'Apr 16' },
    ],
    createdAt: '2026-03-19',
  },
];

export const MOCK_MESSAGES = [
  { id: '1', user: 'Alex Chen', avatar: '👨‍🎬', message: 'Hey team! Just uploaded the revised shot list. Check the files section.', timestamp: '2 hours ago' },
  { id: '2', user: 'Sana Mirza', avatar: '👩', message: 'Love it! The bookstore interior shots look gorgeous. Can we add one more angle for the reveal scene?', timestamp: '1 hour ago' },
  { id: '3', user: 'Jamie Park', avatar: '🧑‍💻', message: 'I can work with that. Also thinking we should shoot the exterior at golden hour for the contrast.', timestamp: '45 min ago' },
  { id: '4', user: 'Alex Chen', avatar: '👨‍🎬', message: 'Great call Jamie. Let\'s plan for 6:30 AM on shoot day 1. Margaret\'s monologue is strongest in that light.', timestamp: '30 min ago' },
  { id: '5', user: 'Sana Mirza', avatar: '👩', message: 'I\'ve been working on my character prep. Should I share the mood board I\'ve been building?', timestamp: '15 min ago' },
];
